[package]
name = "clean-big-targets"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.55", features = ["derive", "env"] }
dialoguer = "0.12.0"
rayon = "1.11.0"

[dev-dependencies]
tempfile = "3.24.0"
