[package]
name = "clean-big-targets"
version = "0.1.0"
edition = "2024"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.53", features = ["derive", "env"] }
dialoguer = "0.12.0"
rayon = "1.11.0"

[dev-dependencies]
tempfile = "3.23.0"
